parameters:
- name: enable_win_cpu
  displayName: 'Whether Windows CPU package is built.'
  type: boolean
  default: true

- name: enable_win_cuda
  displayName: 'Whether Windows CUDA package is built.'
  type: boolean
  default: true

- name: enable_linux_cpu
  displayName: 'Whether Linux CPU package is built.'
  type: boolean
  default: true

- name: enable_linux_cuda
  displayName: 'Whether Linux CUDA package is built.'
  type: boolean
  default: true

- name: enable_win_dml
  displayName: 'Whether Windows DirectML package is built.'
  type: boolean
  default: true

- name: enable_win_arm64_cpu
  displayName: 'Whether Windows ARM64 package is built.'
  type: boolean
  default: true

stages:
- stage: nuget_packaging
  jobs:
    - job: download_capi_artifacts
      pool: 'onnxruntime-Win-CPU-2022'
      steps:
        - ${{ if eq(parameters.enable_win_cpu, true) }}:
          - template: jobs/steps/utils/flex-download-pipeline-artifact.yml
            parameters:
            StepName: 'Download win-cpu-x64 capi Artifacts'
            ArtifactName: onnxruntime-genai-win-cpu-x64-capi
            TargetPath: '$(Build.BinariesDirectory)/artifact-downloads'

    - ${{ if or(eq(parameters.enable_linux_cpu, true), eq(parameters.enable_win_cpu, true), eq(parameters.enable_win_arm64_cpu, true)) }}:
      - template: jobs/nuget-packaging-job.yml
        parameters:
          ep: 'cpu'

    - ${{ if or(eq(parameters.enable_linux_cuda, true), eq(parameters.enable_win_cuda, true)) }}:
      - template: jobs/nuget-packaging-job.yml
        parameters:
          ep: 'cuda'

    - ${{ if eq(parameters.enable_win_dml, true) }}:
      - template: jobs/nuget-packaging-job.yml
        parameters:
          ep: 'directml' 